### ISSUE TITLE
Ошибка в определение класса RetailCrm\\ApiClient

### ISSUE THREAD

**Issue by PanteonWScom** [retailcrm/magento-module#35]
Ошибка в определение класса RetailCrm\\ApiClient в скрипте

[Wed Jan 27 15:24:21.749590 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: PHP Fatal error: Uncaught Error: Class 'RetailCrm\\ApiClient' not found in /var/www/mysite/data/www/mysite.ru/app/code/Retailcrm/Retailcrm/ApiClient/ApiClientFactory.php:16, referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/
[Wed Jan 27 15:24:21.749727 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: Stack trace:, referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/
[Wed Jan 27 15:24:21.750259 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: #0 /var/www/mysite/data/www/mysite.ru/app/code/Retailcrm/Retailcrm/Helper/Proxy.php(89): Retailcrm\\Retailcrm\\ApiClient\\ApiClientFactory->create('https://XXX...', '4vIa0Eyu4IkEAxW...', 'v4'), referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/
[Wed Jan 27 15:24:21.750660 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: #1 /var/www/mysite/data/www/mysite.ru/app/code/Retailcrm/Retailcrm/Model/Config/Backend/ApiUrl.php(143): Retailcrm\\Retailcrm\\Helper\\Proxy->init(), referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/
[Wed Jan 27 15:24:21.751132 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: #2 /var/www/mysite/data/www/mysite.ru/app/code/Retailcrm/Retailcrm/Model/Config/Backend/ApiUrl.php(48): Retailcrm\\Retailcrm\\Model\\Config\\Backend\\ApiUrl->setParams(Array), referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/
[Wed Jan 27 15:24:21.751637 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: #3 /var/www/mysite/data/www/mysite.ru/generated/code/Retailcrm/Retailcrm/Model/Config/Backend/ApiUrl/Interceptor.php(24): Retailcrm\\Retailcrm\\Model\\Config\\Backend\\ApiUrl->beforeSave(), referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/
[Wed Jan 27 15:24:21.752242 2021] [cgi:error] [pid 22576] [client 188.242.xxx.xxx:36212] AH01215: #4 /var/www/mysite/data/www/mysite.ru/vendor/magento/framework/Model/ResourceModel/Db/AbstractDb.php(4 in /var/www/mysite/data/www/mysite.ru/app/code/Retailcrm/Retailcrm/ApiClient/ApiClientFactory.php on line 16, referer: https://www.mysite.ru/XXX2783332/admin/system_config/edit/section/retailcrm/

**Comment by opheugene** [comment]
Модуль был установлен вручную или загружен из маркетплейса?
Установлена ли библиотека https://github.com/retailcrm/api-client-php ?
